NEWS_SUMMARIZER_PROMPT = (
    "News Summarizer Agent Prompt\n"
    "Analyze the following financial news about {ticker} and provide a concise summary focused on potential trading\n"
    "implications:\n"
    "1. Summarize the key points in 5-6 sentences, highlighting any information that could impact {ticker}’s stock price\n"
    "in the short term.\n"
    "2. Identify any positive and negative factors mentioned in the news.\n"
    "3. Based on this news, would you expect the overall sentiment towards {ticker} stock to be bullish, bearish, or\n"
    "neutral? Briefly explain why.\n"
    "News data: {news_data}\n"
    "Please provide your analysis in a clear, concise manner."
)

CHART_ANALYST_PROMPT = (
    "Chart Analyst Agent Prompt\n"
    "Analyze this {ticker} candlestick chart focusing on three trading strategies:\n"
    "1. MACD Crossover Strategy\n"
    "2. KDJ with RSI Filter Strategy\n"
    "For each strategy, provide:\n"
    "1. One key market trend observation\n"
    "2. One potential trading signal\n"
    "Format your response as:\n"
    "Strategy 1: [Trend] | [Signal]\n"
    "Strategy 2: [Trend] | [Signal]\n"
    "Be concise. Limit each observation and signal to 10 words or less.\n"
    "Context (recent candles and indicators):\n{context}"
)

REFLECTION_PROMPT = (
    "Reflection Agent Prompt (Short/Medium-Term)\n"
    "Analyze this {len_data}-day {ticker} stock trading data:\n"
    "{json_data}\n"
    "Focus on:\n"
    "1. Recent recommendations and their outcomes (reward)\n"
    "2. Key factors influencing decisions\n"
    "3. Cumulative return trend\n"
    "Provide three insights:\n"
    "1. Decision effectiveness (based on recommendations and rewards)\n"
    "2. Most impactful key factors\n"
    "3. Short/medium-term return trend\n"
    "Format: [Effectiveness] | [Key Factors] | [Return Trend]\n"
    "Keep each insight under 15 words."
)

TRADING_SIGNAL_CHART_REFLECTION_PROMPT = (
    "Trading Signal Chart Reflection Prompt\n"
    "Analyze this {ticker} trading chart showing closing prices and previous trading signals:\n"
    "- The chart displays closing prices over time\n"
    "- Green markers indicate previous BUY decisions\n"
    "- Red markers indicate previous SELL decisions\n"
    "- Absence of markers indicates HOLD decisions\n"
    "Task:\n"
    "1. Analyze the recent price trend and its relation to previous trading signals.\n"
    "2. Evaluate the effectiveness of recent BUY and SELL decisions based on subsequent price movements.\n"
    "3. Identify any missed opportunities or potential mistakes in recent trading decisions (Be specific).\n"
    "Provide your analysis in a concise, bullet-point format.\n"
    "Context (recent signals and closes):\n{context}"
)

PREDICTION_AGENT_PROMPT = (
    "Prediction Agent Prompt\n"
    "As an advanced trading strategy agent for {ticker} stock, analyze the following data to formulate an opportunistic\n"
    "trading decision:\n"
    "Current Date: {current_date}\n"
    "Current Portfolio:\n"
    "- Shares: {current_shares}\n"
    "- Share Price: ${current_price:.2f}\n"
    "- Average Purchase Price: ${avg_purchase_price:.2f}\n"
    "- Total Value: ${total_value:.2f}\n"
    "- Cash Reserve: ${cash_reserve:.2f}\n"
    "- Cash Percentage: {cash_percentage:.2f}%\n"
    "- Unrealized P/L: ${(current_price - avg_purchase_price) * current_shares:.2f}\n"
    "- Unrealized Profit Percentage: {unrealized_profit_percentage:.2f}%\n"
    "Technical Analysis: {technical_analysis}\n"
    "News Summary: {news_summary}\n"
    "Reflections:\n"
    "- Short-term: {short_term_reflection}\n"
    "- Medium-term: {medium_term_reflection}\n"
    "Effectiveness of past trading decisions: {market_intelligence}\n"
    "Historical Trading Data (Last {len_history} days): {json_data}\n"
    "Based on this data, provide an opportunistic trading strategy. Consider:\n"
    "1. Identify strong upward trends and prioritize holding during these periods.\n"
    "2. Look for buying opportunities during price dips in overall upward trends.\n"
    "3. Consider partial selling to lock in profits while maintaining exposure to further gains.\n"
    "4. Evaluate the effectiveness of past trading decisions from market intelligence.\n"
    "5. Factor in market sentiment, news, and technical indicators for a comprehensive view.\n"
    "6. Balance short-term opportunities with long-term growth potential.\n"
    "Rules:\n"
    "- Maintain at least 10% of the portfolio in cash for opportunistic buying.\n"
    "- Recommend BUY if:\n"
    "a) Strong upward trend and sufficient cash (>10% of portfolio)\n"
    "b) Price dip in overall upward trend and cash reserve above 20%\n"
    "- Recommend SELL if:\n"
    "a) Signs of significant trend reversal, OR\n"
    "b) Exceptional gains (>5% from avg purchase price) for partial sell, OR\n"
    "c) Consistent gains for 3 or more consecutive days\n"
    "- Recommend HOLD if:\n"
    "a) Upward trend continuing without significant reversal signs\n"
    "b) Market uncertainty and current positions are profitable\n"
    "- For BUY: 5-10% in strong upward trends, 1-5% for dip opportunities\n"
    "- For SELL: Consider partial sells (3-5%) to lock in profits\n"
    "- Be more aggressive with SELL during strong upward trends\n"
    "Provide your trading strategy in the following format:\n"
    "Recommendation: [BUY/SELL/HOLD]\n"
    "Position Size: [1-10] (0 if HOLD)\n"
    "Explanation: [Detailed rationale for the decision]\n"
    "Ensure your explanation is detailed and covers all aspects of your analysis and decision-making process, with a\n"
    "focus on capturing opportunistic gains."
)

